const ARTIFACT_COST_TIER = { 350: 1, 700: 2, 1050: 3, 1400: 4, 1750: 5, 2100: 6 };

const KNOWN_ARTIFACTS = new Set([
    "item_arcane_ring_custom",
    "item_ash_legion_shield",
    "item_book_of_shadows_custom",
    "item_ceremonial_robe",
    "item_chipped_vest",
    "item_cloak_of_flames",
    "item_conjurers_catalyst",
    "item_crippling_crossbow",
    "item_dagger_of_ristul",
    "item_dandelion_amulet",
    "item_defiant_shell",
    "item_demonicon_custom",
    "item_desolator_2",
    "item_dezun_bloodrite",
    "item_divine_regalia",
    "item_duelist_gloves",
    "item_enchanters_bauble",
    "item_essence_ring",
    "item_fallen_sky",
    "item_flayers_bota",
    "item_force_boots_custom",
    "item_giant_maul",
    "item_giants_ring",
    "item_greater_faerie_fire_custom",
    "item_gunpowder_gauntlets",
    "item_harmonizer",
    "item_heavy_blade",
    "item_idol_of_screeauk",
    "item_jidi_pollen_bag",
    "item_kobold_cup",
    "item_mana_draught",
    "item_metamorphic_mandible",
    "item_minotaur_horn",
    "item_mirror_shield_custom",
    "item_necronomicon_custom",
    "item_necronomicon_melee_custom",
    "item_occult_bracelet",
    "item_panic_button",
    "item_partisans_brand_custom",
    "item_pogo_stick",
    "item_polliwog_charm",
    "item_poor_mans_shield",
    "item_possessed_mask",
    "item_prophets_pendulum",
    "item_psychic_headband",
    "item_rattlecage",
    "item_riftshadow_prism",
    "item_searing_signet",
    "item_seeds_of_serenity",
    "item_serrated_shiv",
    "item_spell_prism",
    "item_spellslinger",
    "item_spider_legs",
    "item_stormcrafter",
    "item_tome_of_aghanim_custom",
    "item_trusty_shovel_custom",
    "item_unrelenting_eye",
    "item_weighted_dice",
    "item_whisper_of_the_dread",
    "item_woodland_striders_custom",
]);

const ENHANCEMENT_TIERS = {
    "item_enhancement_alert": [1, 2, 3, 4],
    "item_enhancement_brawny": [1, 2, 3, 4],
    "item_enhancement_mystical": [1, 2, 3, 4],
    "item_enhancement_quickened": [1, 2, 3, 4],
    "item_enhancement_tough": [1, 2, 3, 4],
    "item_enhancement_keen_eyed": [2, 3],
    "item_enhancement_vast": [2, 3],
    "item_enhancement_greedy": [2, 3],
    "item_enhancement_wise": [2, 3],
    "item_enhancement_vampiric": [2, 3, 4],
    "item_enhancement_timeless": [4, 5],
    "item_enhancement_crude": [4, 5],
    "item_enhancement_titanic": [4, 5],
    "item_enhancement_feverish": [4, 5],
    "item_enhancement_evolved": [5, 6],
    "item_enhancement_fleetfooted": [5, 6],
    "item_enhancement_boundless": [5, 6],
    "item_enhancement_audacious": [5, 6],
};

const ENHANCEMENTS_SINCE = "1.03";

module.exports = { ARTIFACT_COST_TIER, KNOWN_ARTIFACTS, ENHANCEMENT_TIERS, ENHANCEMENTS_SINCE };
